django/pong/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from pong import views

urlpatterns = [
    path('', views.game, name='game'),
    path('game/normal/', views.game_normal, name='game_normal'),
    path('game/tournament-4/', views.game_tournament_4, name='game_tournament_4'),
    path('game/tournament-8/', views.game_tournament_8, name='game_tournament_8'),
    path('game/save/', views.game_save, name='game_save'),
    path('game/history/', views.game_history, name='game_history'),
    path('friends/', views.friends, name='friends'),
    path('friend-delete/', views.friend_delete, name='friend_delete'),
    path('friend-requests/', views.friend_requests, name='friend_requests'),
    path('friend-request-accept/', views.friend_request_accept, name='friend_request_accept'),
    path('friend-request-reject/', views.friend_request_reject, name='friend_request_reject'),
    path('friend-request-delete/', views.friend_request_delete, name='friend_request_delete'),
    path('update-last-login/', views.update_last_login, name='update_last_login'),
    path('profile/', views.profile, name='profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('account-data/', views.account_data, name='account_data'),
    path('download-account/', views.download_account, name='download_account'),
    path('delete-account/', views.delete_account, name='delete_account'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('oauth/login/', views.oauth_login, name='oauth_login'),
    path('oauth/callback/', views.oauth_callback, name='oauth_callback'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy')
]

django/pong/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, MaxLengthValidator
from .models import PongUser


class SigninForm(forms.Form):
    username = forms.CharField(
        label='Username',
        required=True,
        min_length=3,
        max_length=30
    )
    password = forms.CharField(
        widget=forms.PasswordInput,
        label='Password',
        required=True,
        min_length=3,
        max_length=30
    )

    def __init__(self, *args, **kwargs):
        super(SigninForm, self).__init__(*args, **kwargs)

        # Tüm form alanlarına bootstrap classları veriyoruz
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
            # Autocapitalize özniteliğini kaldır, Chrome dışında desteklenmiyor
            if 'autocapitalize' in visible.field.widget.attrs:
                del visible.field.widget.attrs['autocapitalize']

        # Eğer hata varsa daha net görülmesi için bootstrap class'ı ekliyoruz
        if self.errors:
            for key in self.errors:
                self.fields[key].widget.attrs['class'] += ' is-invalid'

    def clean_username(self):
        invalid_endings = ['ecole', 'ecole42', 'ecole_42']
        username = self.cleaned_data.get('username')
        if username and username.endswith(tuple(invalid_endings)):
            raise ValidationError("The username must not end with ecole or ecole42.")
        return username

    def clean(self):
        cleaned_data = super().clean()

        for key, name in list(cleaned_data.items()):
            if not isinstance(name, str):
                continue
            if any(c.isspace() for c in name):
                self.add_error(key, "This field cannot contain spaces.")

        return cleaned_data


class SignupForm(UserCreationForm):
    privacy_policy = forms.BooleanField(
        required=True,
        error_messages={'required': 'You have to accept our privacy policy.'}
    )

    class Meta(UserCreationForm.Meta):
        model = PongUser
        fields = ['username', 'password1', 'password2', 'display_name', 'first_name', 'last_name', 'avatar']

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)

        # Minimum ve Maximum karakter sayısı olsun
        self.fields['password1'].validators.extend([
            MinLengthValidator(3),
            MaxLengthValidator(30),
        ])

        # Tüm form alanlarına bootstrap classları veriyoruz
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
            # Autocapitalize özniteliğini kaldır, Chrome dışında desteklenmiyor
            if 'autocapitalize' in visible.field.widget.attrs:
                del visible.field.widget.attrs['autocapitalize']

        # Eğer hata varsa daha net görülmesi için bootstrap class'ı ekliyoruz
        if self.errors:
            for key in self.errors:
                self.fields[key].widget.attrs['class'] += ' is-invalid'

    def clean_username(self):
        invalid_endings = ['ecole', 'ecole42', 'ecole_42']
        username = super().clean_username()
        if username and username.endswith(tuple(invalid_endings)):
            raise ValidationError("The username must not end with ecole, ecole42 or ecole_42.")
        return username

    def clean_display_name(self):
        invalid_endings = ['ecole', 'ecole42', 'ecole_42']
        display_name = self.cleaned_data.get('display_name')
        if display_name and display_name.endswith(tuple(invalid_endings)):
            raise forms.ValidationError("The display name must not end with ecole, ecole42 or ecole_42.")
        return display_name

    def clean(self):
        cleaned_data = super().clean()

        for key, name in list(cleaned_data.items()):
            if not isinstance(name, str):
                continue
            if any(c.isspace() for c in name):
                self.add_error(key, "This field cannot contain spaces.")

        return cleaned_data


class ProfileForm(forms.ModelForm):
    class Meta:
        model = PongUser
        fields = ['first_name', 'last_name', 'display_name', 'avatar']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        # Tüm form alanlarına bootstrap classları veriyoruz
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
            # Autocapitalize özniteliğini kaldır, Chrome dışında desteklenmiyor
            if 'autocapitalize' in visible.field.widget.attrs:
                del visible.field.widget.attrs['autocapitalize']

        # Eğer hata varsa daha net görülmesi için bootstrap class'ı ekliyoruz
        if self.errors:
            for key in self.errors:
                self.fields[key].widget.attrs['class'] += ' is-invalid'

    def clean_display_name(self):
        invalid_endings = ['ecole', 'ecole42', 'ecole_42']
        display_name = self.cleaned_data.get('display_name')
        username = self.instance.username

        if display_name.endswith(tuple(invalid_endings)) and not username.endswith('@ecole'):
            raise forms.ValidationError("The display name must not end with ecole or ecole42.")
        return display_name

    def clean(self):
        cleaned_data = super().clean()

        for key, name in list(cleaned_data.items()):
            if not isinstance(name, str):
                continue
            if any(c.isspace() for c in name):
                self.add_error(key, "This field cannot contain spaces.")

        return cleaned_data


class PassChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(PassChangeForm, self).__init__(*args, **kwargs)

        # Minimum ve Maximum karakter sayısı olsun
        self.fields['new_password1'].validators.extend([
            MinLengthValidator(3),
            MaxLengthValidator(30),
        ])

        # Tüm form alanlarına bootstrap classları veriyoruz
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
            # Autocapitalize özniteliğini kaldır, Chrome dışında desteklenmiyor
            if 'autocapitalize' in visible.field.widget.attrs:
                del visible.field.widget.attrs['autocapitalize']

        # Eğer hata varsa daha net görülmesi için bootstrap class'ı ekliyoruz
        if self.errors:
            for key in self.errors:
                self.fields[key].widget.attrs['class'] += ' is-invalid'

    def clean(self):
        cleaned_data = super().clean()

        for key, name in list(cleaned_data.items()):
            if not isinstance(name, str):
                continue
            if any(c.isspace() for c in name):
                self.add_error(key, "This field cannot contain spaces.")

        return cleaned_data


class FriendshipRequestForm(forms.Form):
    to_username = forms.CharField(
        label='Username',
        required=True,
        min_length=3,
        max_length=30
    )

    def __init__(self, *args, **kwargs):
        super(FriendshipRequestForm, self).__init__(*args, **kwargs)

        # Tüm form alanlarına bootstrap classları veriyoruz
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
            # Autocapitalize özniteliğini kaldır, Chrome dışında desteklenmiyor
            if 'autocapitalize' in visible.field.widget.attrs:
                del visible.field.widget.attrs['autocapitalize']

        # Eğer hata varsa daha net görülmesi için bootstrap class'ı ekliyoruz
        if self.errors:
            for key in self.errors:
                self.fields[key].widget.attrs['class'] += ' is-invalid'

    def clean(self):
        cleaned_data = super().clean()

        for key, name in list(cleaned_data.items()):
            if not isinstance(name, str):
                continue
            if any(c.isspace() for c in name):
                self.add_error(key, "This field cannot contain spaces.")

        return cleaned_data


class HistoryForm(forms.Form):
    username = forms.CharField(
        label='Username',
        required=True,
        min_length=3,
        max_length=30
    )

    def __init__(self, *args, **kwargs):
        super(HistoryForm, self).__init__(*args, **kwargs)

        # Tüm form alanlarına bootstrap classları veriyoruz
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
            # Autocapitalize özniteliğini kaldır, Chrome dışında desteklenmiyor
            if 'autocapitalize' in visible.field.widget.attrs:
                del visible.field.widget.attrs['autocapitalize']

        # Eğer hata varsa daha net görülmesi için bootstrap class'ı ekliyoruz
        if self.errors:
            for key in self.errors:
                self.fields[key].widget.attrs['class'] += ' is-invalid'

    def clean(self):
        cleaned_data = super().clean()

        for key, name in list(cleaned_data.items()):
            if not isinstance(name, str):
                continue
            if any(c.isspace() for c in name):
                self.add_error(key, "This field cannot contain spaces.")

        return cleaned_data


class DynamicPlayerForm(forms.Form):
    def __init__(self, *args, **kwargs):

django/templates/account_data.html
{% extends "base.html" %}

{% load static %}

{% block meta %}
	<meta name="description" content="Manage your account data with ease. Download your personal data or delete your account and all associated data.">
	<meta name="keywords" content="account data, data privacy, download data, delete account, data security, personal data">
{% endblock %}

{% block title %}
	Pong | Account Data
{% endblock %}

{% block content %}
	<div class="container-fluid my-4">
		<div class="row justify-content-center align-items-center">
			<div id="accountDataElement"
				class="col-11 col-sm-10 col-md-9 col-lg-8 col-xl-7 col-xxl-6 p-4 rounded-4 bg-body shadow text-center">
				<h3>Account Data</h3>
				<p>
					Your data security is important to us. On this page, you can manage your account information.
					You have the option to download your personal data or delete your account entirely.
					Please carefully consider your actions, as deleting your account will permanently remove all
					associated data.
				</p>
				<hr>
				<div class="mt-3">
					<h5>Download Account Data</h5>
					<p>
						You can delete your account. When you delete your account, all your information will be deleted,
						including your profile information, game registration and friends.
					</p>
					<button id="downloadAccountDataButton" type="button" class="btn btn-dark w-auto">
						Download Account Data
					</button>
				</div>
				<hr>
				<div class="mt-3">
					<h5>Delete Account with Data</h5>
					<p>
						You can delete your account. When you delete your account, all your information will be deleted,
						including your profile information, game registration and friends.
					</p>
					<ul class="list-unstyled fw-bold text-start mt-3">
						<li>
							Warning: If you delete your account you will be logged out.
						</li>
						<li>
							Warning: If you are logged in via Ecole, your account will be deleted,
							but the permission you gave for your Intra account will still be valid.
							If you want to remove the permission, you must do it via Intra.
						</li>
					</ul>
					{% csrf_token %}
					<button id="deleteAccountButton" type="button" class="btn btn-danger w-auto">
						Delete Account
					</button>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

django/templates/change_password.html
{% extends "base.html" %}

{% load static %}

{% block meta %}
    <meta name="description" content="Change your password to ensure your 3D Pong game account remains secure.">
    <meta name="keywords" content="3D Pong, password change, account security, update password">
{% endblock %}

{% block title %}
    Pong | Change Password
{% endblock %}

{% block content %}
    <div class="d-flex flex-column justify-content-center align-items-center my-auto">
        <div class="col-11 col-sm-9 col-md-7 col-lg-6 col-xl-5 col-xxl-4 p-4 my-5 bg-body rounded-4 shadow">
            <form id="changePasswordForm" method="post" enctype="application/x-www-form-urlencoded"
                  action="{% url 'change_password' %}" novalidate>
                {% csrf_token %}
                <div class="text-center mb-3">
                    {% if user.avatar %}
                        <img src="{{ user.avatar.url }}" alt="avatar" class="avatar-big img-thumbnail">
                    {% else %}
                        <img src="{% static 'images/default_avatar.jpg' %}" alt="avatar"
                             class="avatar-big img-thumbnail">
                    {% endif %}
                    <h5>{{ user.username }}</h5>
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text"><i class="bi bi-lock-fill"></i></span>
                    {{ form.old_password }}
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text"><i class="bi bi-key-fill"></i></span>
                    {{ form.new_password1 }}
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text"><i class="bi bi-key-fill"></i></span>
                    {{ form.new_password2 }}
                </div>
                <button type="submit" class="btn btn-dark w-100 mt-2">
                    Change Password
                </button>
            </form>
        </div>
    </div>
{% endblock %}

django/templates/friend_requests.html
{% extends "base.html" %}

{% load static %}

{% block meta %}
    <meta name="description" content="Connect with other players by sending friend requests in the 3D Pong game.">
    <meta name="keywords" content="3D Pong, send friend request, gaming community, connect with friends">
{% endblock %}

{% block title %}
    Pong | Friend Requests
{% endblock %}

{% block content %}
    <div class="container-fluid my-4">
        <div class="row justify-content-center align-items-center gap-5">
            <div class="col-11 col-md-10 col-lg-9 col-xl-8 col-xxl-7 p-4 rounded-4 bg-body shadow">
                <h3 class="text-center mb-4">
                    Outgoing Friend Requests
                </h3>
                <form id="sendFriendRequestForm" method="post" enctype="application/x-www-form-urlencoded"
                      action="{% url 'friend_requests' %}" novalidate>
                    {% csrf_token %}
                    <div class="input-group">
                        {{ form.to_username }}
                        <button type="submit" class="btn btn-dark">
                            <i class="bi bi-plus-lg"></i>
                        </button>
                    </div>
                </form>
                <div class="table-responsive mt-3">
                    <table class="table text-center table-hover my-auto">
                        <thead>
                        <tr>
                            <th>Username</th>
                            <th>Display Name</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for friend in sent_requests %}
                            <tr id="friendship-{{ friend.friendship_id }}">
                                <td>{{ friend.username }}</td>
                                <td>{{ friend.display_name }}</td>
                                <td>{{ friend.first_name }}</td>
                                <td>{{ friend.last_name }}</td>
                                <td>
                                    <i class="bi bi-trash-fill cursor-pointer text-danger"
                                       onclick="deleteFriendRequest('{{ friend.friendship_id }}')">
                                    </i>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-11 col-md-10 col-lg-9 col-xl-8 col-xxl-7 p-4 rounded-4 bg-body shadow">
                <h3 class="text-center mb-4">
                    Incoming Friend Requests
                </h3>
                <div class="table-responsive">
                    <table class="table text-center table-hover my-auto">
                        <thead>
                        <tr>
                            <th>Username</th>
                            <th>Display Name</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Accept</th>
                            <th>Reject</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for friend in received_requests %}
                            <tr id="friendship-{{ friend.friendship_id }}">
                                <td>{{ friend.username }}</td>
                                <td>{{ friend.display_name }}</td>
                                <td>{{ friend.first_name }}</td>
                                <td>{{ friend.last_name }}</td>
                                <td>
                                    <i class="bi bi-check-lg cursor-pointer text-success"
                                       onclick="acceptFriendRequest('{{ friend.friendship_id }}')"></i>
                                </td>
                                <td>
                                    <i class="bi bi-x-lg cursor-pointer text-danger"
                                       onclick="rejectFriendRequest('{{ friend.friendship_id }}')"></i>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

django/templates/friends.html
{% extends "base.html" %}

{% load static %}

{% block meta %}
    <meta name="description" content="View and manage your friends in the 3D Pong game.">
    <meta name="keywords" content="3D Pong, friends list, manage friends, gaming network">
{% endblock %}

{% block title %}
    Pong | Friends
{% endblock %}

{% block content %}
    <div class="container-fluid my-4">
        <div class="row justify-content-center align-items-center">
            <div class="col-11 col-md-10 col-lg-9 col-xl-8 col-xxl-7 p-4 rounded-4 bg-body shadow">
                <h3 class="text-center mb-4">
                    Friend List
                </h3>
                <div class="table-responsive">
                    <table class="table text-center table-hover my-auto">
                        <thead>
                        <tr>
                            <th>Username</th>
                            <th>Display Name</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Status</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for friend in user_friends %}
                            <tr id="friendship-{{ friend.friendship_id }}">
                                <td>{{ friend.username }}</td>
                                <td>{{ friend.display_name }}</td>
                                <td>{{ friend.first_name }}</td>
                                <td>{{ friend.last_name }}</td>
                                {% if friend.status == "online" %}
                                    <td class="text-success fw-semibold">Online</td>
                                {% else %}
                                    <td class="text-danger fw-semibold">Offline</td>
                                {% endif %}
                                <td>
									{% csrf_token %}
                                    <i class="bi bi-trash-fill cursor-pointer text-danger"
                                       onclick="deleteFriend('{{ friend.friendship_id }}')">
									</i>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

django/templates/game.html
{% extends "base.html" %}

{% load static %}

{% block meta %}
    <meta name="description"
          content="Choose your preferred game mode in the 3D Pong game. Play 1v1 or create a tournament">
    <meta name="keywords" content="3D Pong, game mode selection, 1v1, tournament, game options">
{% endblock %}

{% block title %}
    Pong | Game
{% endblock %}

{% block content %}
    <div class="container-fluid my-4">
        <div class="row justify-content-center align-items-center">
            <div class="col-11 col-sm-11 col-md-9 col-lg-8 col-xl-7 col-xxl-5 p-4 bg-body rounded-4 shadow text-center">
                <img class="img-fluid mb-3" width="75" src="{% static 'images/logo.png' %}" alt="Pong Logo">
                <h5>Welcome to the 3D Pong Game.</h5>
                <hr>
                <p>
                    The game has Normal (1v1) and Tournament mode.<br>
                    <span class="fw-semibold text-decoration-underline">
                        All games are saved only on behalf of the logged-in user.
                    </span>
                </p>
                <p>
                    The above rule also applies to Tournament mode.<br>
                    Each game played and completed by the logged in player is saved.
                </p>
                <p class="fw-semibold text-decoration-underline">
                    The Tournament does not need to end for these games to be saved.<br>
                    Finished games are saved even if the tournament is incomplete.
                </p>
                <hr>
                <div class="vstack align-items-center gap-4 mt-4">
                    <a href="{% url 'game_normal' %}" class="btn btn-dark w-50">Normal (1v1)</a>
                    <a href="{% url 'game_tournament_4' %}" class="btn btn-dark w-50">Tournament (4)</a>
                    <a href="{% url 'game_tournament_8' %}" class="btn btn-dark w-50">Tournament (8)</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

django/templates/game_history.html
{% extends "base.html" %}

{% load static %}

{% block meta %}
    <meta name="description" content="Review your game history in the 3D Pong game. See the games you've played and the results.">
    <meta name="keywords" content="3D Pong, game history, match results, player stats, gaming records">
{% endblock %}

{% block title %}
    Pong | Game History
{% endblock %}

{% block content %}
    <div class="container-fluid my-4">
        <div class="row justify-content-center align-items-center">
            <div class="col-11 col-md-11 col-lg-10 col-xl-9 col-xxl-7 p-4 rounded-4 bg-body shadow">
                <h3 class="text-center mb-4">
                    Game History
                </h3>
                <form id="historyForm" method="post" enctype="application/x-www-form-urlencoded"
                      action="{% url 'game_history' %}" novalidate>
                    {% csrf_token %}
                    <div class="input-group">
                        {{ form.username }}
                        <button type="submit" class="btn btn-dark">
                            <i class="bi bi-search"></i>
                        </button>
                    </div>
                </form>
                <div class="table-responsive mt-3">
                    <table class="table text-center table-hover my-auto">
                        <thead>
                        <tr>
                            <th>User Name</th>
                            <th>User Display Name</th>
                            <th>Rival Display Name</th>
                            <th>Status</th>
                            <th>DateTime</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

django/templates/signup.html
{% extends "base.html" %}

{% load static %}

{% block meta %}
    <meta name="description" content="Create a new account for the 3D Pong game.">
    <meta name="keywords" content="3D Pong, sign up, create account, register, join game">
{% endblock %}

{% block title %}
    Pong | Sign Up
{% endblock %}

{% block content %}
    <div class="d-flex flex-column justify-content-center align-items-center my-auto">
        <div class="col-11 col-sm-10 col-md-8 col-lg-7 col-xl-6 col-xxl-4 p-4 my-5 bg-body rounded-4 shadow">
            <form id="signupForm" method="post" enctype="multipart/form-data" action="{% url 'signup' %}" novalidate>
                {% csrf_token %}
                <div class="text-center mb-4">
                    <img class="img-fluid mb-1" width="50" src="{% static 'images/logo.png' %}" alt="Pong Logo">
                    <h3>Create Account</h3>
                    <span class="text-muted">
                        Already have an account?
                    </span>
                    <a class="link-offset-2 link-underline link-underline-opacity-0 link-underline-opacity-100-hover"
                       href="{% url 'signin' %}">
                        Sign In here
                    </a>
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text"><i class="bi bi-person-fill-lock"></i></span>
                    {{ form.username }}
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text"><i class="bi bi-key-fill"></i></span>
                    {{ form.password1 }}
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text"><i class="bi bi-key-fill"></i></span>
                    {{ form.password2 }}
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text"><i class="bi bi-eye-fill"></i></span>
                    {{ form.display_name }}
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text"><i class="bi bi-person-vcard-fill"></i></span>
                    {{ form.first_name }}
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text"><i class="bi bi-person-vcard-fill"></i></span>
                    {{ form.last_name }}
                </div>
                <div class="input-group">
                    <span class="input-group-text"><i class="bi bi-person-bounding-box"></i></span>
                    {{ form.avatar }}
                </div>
                <div class="form-text fw-semibold fst-italic mb-4">
                    If no avatar is selected, the default avatar will be displayed.
                </div>
                <div class="form-check fw-semibold mb-3">
                    <input class="form-check-input" type="checkbox" name="privacy_policy" id="id_privacy_policy"
                           required>
                    <label class="form-check-label" for="id_privacy_policy">
                        I have read and agree to the website
                    </label>
                    <span id="privacyPolicy" class="text-primary text-decoration-underline cursor-pointer">
                        Privacy Policy
                    </span>
                </div>
                <button type="submit" class="btn btn-dark w-100 mt-2">
                    Sign Up
                </button>
            </form>
        </div>
    </div>

    <div id="privacyPolicyModal" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">
                        <i class="bi bi-shield-fill-check me-1"></i>
                        Privacy Policy
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    {% include "privacy_policy_text.html" %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}